version: 2

build:
 os: "ubuntu-24.04"
 tools:
   python: "3"
   rust: "latest"
 jobs:
   pre_install:
     - pip install mkdocstrings-python zensical maturin
   pre_build:
     - maturin build --release
     - pip install target/wheels/*.whl
   build:
     html:
       - zensical build
   post_build:
     - mkdir -p $READTHEDOCS_OUTPUT/html/
     - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
