version: 2

build:
 os: "ubuntu-24.04"
 tools:
   python: "3"
   rust: "latest"
 jobs:
   pre_install:
     - pip install mkdocs-material mkdocstrings[python] maturin
   pre_build:
     - maturin build --release
     - pip install target/wheels/*.whl

mkdocs:
 configuration: mkdocs.yml
