version: 2

build:
 os: "ubuntu-24.04"
 tools:
   python: "3"
 jobs:
   pre_install:
     - pip install mkdocs-material mkdocstrings[python] maturin
   pre_build:
     - maturin build --release
   post_build:
     - cp target/wheels/*.whl docs/

mkdocs:
 configuration: mkdocs.yml
